# SSN Airrohr Firmware CI workflow

name: beta-ssn build status

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master-ssn branch
  push:
    branches: [ beta-ssn ]
  create:
    branches: [ beta-ssn ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          
      - name: Load dependencies from cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install platformio
          platformio --version
          
      - name: Run builds
        run: |
          cd airrohr-firmware && pwd && ls -l && platformio run && ls -l builds/
          cd ../airrohr-update-loader && pwd && ls -l && platformio run && ls -l builds/
        
      # - name: Upload Release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "../airrohr-firmware/builds/*"
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     # Instead add tags through every Release related commit
      #     # tag: vSSN-NRZ-2021-134-B5 
